Switch to clang.
This results in a much more readable error:
c++ -std=c++11 -DHAVE_CONFIG_H -I. -I/usr/ports/pobj/protobuf-3.2.0/protobuf-3.2.0/src -I.. -pthread -DHAVE_PTHREAD=1 -DHAVE_ZLIB=1 -Wall -Wno-sign-compare -O2 -pipe -MT google/protobuf/compiler/code_generator.lo -MD -MP -MF google/protobuf/compiler/.deps/code_generator.Tpo -c /usr/ports/pobj/protobuf-3.2.0/protobuf-3.2.0/src/google/protobuf/compiler/code_generator.cc -fPIC -DPIC -o google/protobuf/compiler/.libs/code_generator.o
In file included from /usr/ports/pobj/protobuf-3.2.0/protobuf-3.2.0/src/google/protobuf/compiler/code_generator.cc:37:
/usr/ports/pobj/protobuf-3.2.0/protobuf-3.2.0/src/google/protobuf/compiler/plugin.pb.h:238:29: error:
      expected ')'
  ::google::protobuf::int32 major() const;
                            ^
/usr/include/sys/types.h:212:45: note: expanded from macro 'major'