Incomplete port of hledger.
Build broken by something very similar to
https://gitlab.haskell.org/ghc/ghc/-/issues/17755

Hledger/Cli/DocFiles.hs:44:6: error:
    * Exception when trying to run compile-time code:
        /home/greg/ports/pobj/hledger-1.19/hledger-1.19/embeddedfiles/hledger.info: hGetContents: invalid argument (invalid byte sequence)
      Code: embedFileRelative "embeddedfiles/hledger.info"
    * In the untyped splice:
        $(embedFileRelative "embeddedfiles/hledger.info")
   |
44 |     ,$(embedFileRelative "embeddedfiles/hledger.info")
   |      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
cabal: Failed to build hledger-1.19 (which is required by exe:hledger from
hledger-1.19).